spring:
  data:
    mongodb:
      # host: localhost
      host: j7c204.p.ssafy.io
      port: 27017
      #      authentication-database: admin
      #      username: j7c204
      #      password: seveneleven
      database: test

#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/test